/******************************
 * Table du modèle processus. *
 ******************************/
CREATE TABLE PRC_PROCESSUS
(
  PRC_ID          INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PRC_NOM         VARCHAR(48)      NOT NULL,
  PRC_DESCRIPTION TEXT             NULL,
  PRC_NOMAUTEUR   VARCHAR(48)      NULL,
  PRC_MAILAUTEUR  VARCHAR(32)      NULL,
  PRIMARY KEY PK_PRC_PROCESSUS (PRC_ID)
) ;


CREATE TABLE COM_COMPOSANT
(
  COM_ID          INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  COM_NOM         VARCHAR(48)      NOT NULL,
  COM_DESCRIPTION TEXT             NULL,
  COM_NOMAUTEUR   VARCHAR(48)      NULL,
  COM_MAILAUTEUR  VARCHAR(32)      NULL,
  COM_PRC_ID      INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_COM_COMPOSANT (COM_ID),
  FOREIGN KEY FK_COM_PRC (COM_PRC_ID) REFERENCES PRC_PROCESSUS (PRC_ID)
) ;


CREATE TABLE DFT_DEFINITIONTRAVAIL
(
  DFT_ID          INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DFT_NOM         VARCHAR(48)      NOT NULL,
  DFT_DESCRIPTION TEXT             NULL,
  DFT_COM_ID      INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_DFT_DEFINITIONTRAVAIL (DFT_ID),
  FOREIGN KEY FK_DFT_COM (DFT_COM_ID) REFERENCES COM_COMPOSANT (COM_ID)
) ;


CREATE TABLE ACT_ACTIVITE
(
  ACT_ID          INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ACT_NOM         VARCHAR(48)      NOT NULL,
  ACT_DESCRIPTION TEXT             NULL,
  ACT_DFT_ID      INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_ACT_ACTIVITE (ACT_ID),
  FOREIGN KEY FK_ACT_DFT (ACT_DFT_ID) REFERENCES DFT_DEFINITIONTRAVAIL (DFT_ID)
) ;


CREATE TABLE ROL_ROLE
(
  ROL_ID          INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ROL_NOM         VARCHAR(48)      NOT NULL,
  ROL_DESCRIPTION TEXT             NULL,
  ROL_COM_ID      INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_ROL_ROLE (ROL_ID),
  FOREIGN KEY FK_ROL_COM (ROL_COM_ID) REFERENCES COM_COMPOSANT (COM_ID)
) ;


CREATE TABLE PRD_PRODUIT
(
  PRD_ID          INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PRD_NOM         VARCHAR(48)      NOT NULL,
  PRD_DESCRIPTION TEXT             NULL,
  PRD_COM_ID      INTEGER UNSIGNED NOT NULL,
  PRD_ROL_ID      INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_PRD_PRODUIT (PRD_ID),
  FOREIGN KEY FK_PRD_COM (PRD_COM_ID) REFERENCES COM_COMPOSANT (COM_ID),
  FOREIGN KEY FK_PRD_ROL (PRD_ROL_ID) REFERENCES ROL_ROLE (ROL_ID)
) ;


CREATE TABLE R01_ACT_PRD_ENTREE
(
  R01_ACT_ID INTEGER UNSIGNED NOT NULL,
  R01_PRD_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_R01_ACT_PRD_ENTREE (R01_ACT_ID, R01_PRD_ID),
  FOREIGN KEY FK_R01_ACT (R01_ACT_ID) REFERENCES ACT_ACTIVITE (ACT_ID),
  FOREIGN KEY FK_R01_PRD (R01_PRD_ID) REFERENCES PRD_PRODUIT (PRD_ID)
) ;


CREATE TABLE R02_ACT_PRD_SORTIE
(
  R02_ACT_ID INTEGER UNSIGNED NOT NULL,
  R02_PRD_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_R02_ACT_PRD_SORTIE (R02_ACT_ID, R02_PRD_ID),
  FOREIGN KEY FK_R02_ACT (R02_ACT_ID) REFERENCES ACT_ACTIVITE (ACT_ID),
  FOREIGN KEY FK_R02_PRD (R02_PRD_ID) REFERENCES PRD_PRODUIT (PRD_ID)
) ;


CREATE TABLE R03_ACT_ROL
(
  R03_ACT_ID  INTEGER UNSIGNED NOT NULL,
  R03_ROL_ID  INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_R03_ACT_ROL (R03_ACT_ID, R03_ROL_ID),
  FOREIGN KEY FK_R03_ACT (R03_ACT_ID) REFERENCES ACT_ACTIVITE (ACT_ID),
  FOREIGN KEY FK_R03_ROL (R03_ROL_ID) REFERENCES ROL_ROLE (ROL_ID)
) ;






/******************************
 * Table du modèle exécution. *
 ******************************/
CREATE TABLE PRJ_PROJET
(
  PRJ_ID              INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PRJ_NOM             VARCHAR(48)      NOT NULL,
  PRJ_DESCRIPTION     TEXT             NULL,
  PRJ_DATEDEBUTPREVUE DATE             NULL,
  PRJ_DATEFINPREVUE   DATE             NULL,
  PRJ_PRC_ID          INTEGER UNSIGNED NOT NULL,
  PRJ_COL_ID_CHEF     INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_PRJ_PROJET (PRJ_ID),
  FOREIGN KEY FK_PRJ_PRC (PRJ_PRC_ID) REFERENCES PRC_PROCESSUS (PRC_ID)
) ;


CREATE TABLE ITE_ITERATION
(
  ITE_ID              INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ITE_NUMERO          INTEGER UNSIGNED NOT NULL,
  ITE_NOM             VARCHAR(48)      NOT NULL,
  ITE_DATEDEBUTPREVUE DATE             NOT NULL,
  ITE_DATEFINPREVUE   DATE             NOT NULL,
  ITE_DATEDEBUTREELLE DATE             NULL,
  ITE_DATEFINREELLE   DATE             NULL,
  ITE_ETAT            INTEGER UNSIGNED NULL,
  ITE_PRJ_ID          INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_ITE_ITERATION (ITE_ID),
  FOREIGN KEY FK_ITE_PRJ (ITE_PRJ_ID) REFERENCES PRJ_PROJET (PRJ_ID)
) ;


CREATE TABLE COL_COLLABORATEUR
(
  COL_ID           INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  COL_NOM          VARCHAR(32)      NOT NULL,
  COL_PRENOM       VARCHAR(32)      NOT NULL,
  COL_ADRESSE      VARCHAR(256)     NULL,
  COL_TELEPHONE    VARCHAR(24)      NULL,
  COL_PORTABLE     VARCHAR(24)      NULL,
  COL_EMAIL        VARCHAR(48)      NULL,
  COL_COMMENTAIRES TEXT             NULL,
  COL_UTILISATEUR  VARCHAR(24)      NOT NULL,
  COL_MOTDEPASSE   VARCHAR(24)      NOT NULL,
  COL_TACHEENCOURS INTEGER UNSIGNED NOT NULL,
  COL_DROIT        INTEGER UNSIGNED NULL,
  PRIMARY KEY PK_COL_COLLABORATEUR (COL_ID)
) ;


CREATE TABLE TAC_TACHE
(
  TAC_ID              INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TAC_NOM             VARCHAR(48)      NOT NULL,
  TAC_DESCRIPTION     VARCHAR(48)      NULL,
  TAC_CHARGEINITIALE  FLOAT            NOT NULL,
  TAC_TEMPSPASSE      FLOAT            NOT NULL,
  TAC_RESTEAPASSER    FLOAT            NOT NULL,
  TAC_ETAT            INTEGER          NOT NULL,
  TAC_DATEDEBUTPREVUE DATE             NOT NULL,
  TAC_DATEFINPREVUE   DATE             NOT NULL,
  TAC_DATEDEBUTREELLE DATE             NULL,
  TAC_DATEFINREELLE   DATE             NULL,
  TAC_ITE_ID          INTEGER UNSIGNED NOT NULL,
  TAC_COL_ID          INTEGER UNSIGNED NOT NULL,
  TAC_ACT_ID          INTEGER UNSIGNED NULL,
  TAC_DATEDEBUTCHRONO DATE             NULL,
  PRIMARY KEY PK_TAC_TACHE (TAC_ID),
  FOREIGN KEY FK_TAC_ITE (TAC_ITE_ID) REFERENCES ITE_ITERATION (ITE_ID),
  FOREIGN KEY FK_TAC_COL (TAC_COL_ID) REFERENCES COL_COLLABORATEUR (COL_ID),
  FOREIGN KEY FK_TAC_ACT (TAC_ACT_ID) REFERENCES ACT_ACTIVITE (ACT_ID)
) ;


CREATE TABLE ART_ARTEFACT
(
  ART_ID            INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ART_NOM           VARCHAR(48)      NOT NULL,
  ART_DESCRIPTION   TEXT             NULL,
  ART_NOM_FICHIER   VARCHAR(48)      NULL,
  ART_PRJ_ID        INTEGER UNSIGNED NOT NULL,
  ART_COL_ID        INTEGER UNSIGNED NOT NULL,
  ART_TAC_ID_ENTREE INTEGER UNSIGNED NULL,
  ART_TAC_ID_SORTIE INTEGER UNSIGNED NULL,
  ART_PRD_ID        INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_ART_ARTEFACT (ART_ID),
  FOREIGN KEY FK_ART_PRJ        (ART_PRJ_ID)        REFERENCES PRJ_PROJET (PRJ_ID),
  FOREIGN KEY FK_ART_COL        (ART_COL_ID)        REFERENCES COL_COLLABORATEUR (COL_ID),
  FOREIGN KEY FK_ART_TAC_ENTREE (ART_TAC_ID_ENTREE) REFERENCES TAC_TACHE (TAC_ID),
  FOREIGN KEY FK_ART_TAC_SORTIE (ART_TAC_ID_SORTIE) REFERENCES TAC_TACHE (TAC_ID),
  FOREIGN KEY FK_ART_PRD        (ART_PRD_ID)        REFERENCES PRD_PRODUIT (PRD_ID)
) ;


CREATE TABLE CND_CONDITION
(
  CND_ID          INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CND_TAC_ID      INTEGER UNSIGNED NOT NULL,
  CND_TAC_ID_PREC INTEGER UNSIGNED NOT NULL,
  CND_ETAT        INTEGER          NOT NULL,
  PRIMARY KEY PK_COL_ROL      (CND_ID),
  FOREIGN KEY FK_CND_TAC      (CND_TAC_ID)      REFERENCES TAC_TACHE (TAC_ID),
  FOREIGN KEY FK_CND_TAC_PREC (CND_TAC_ID_PREC) REFERENCES TAC_TACHE (TAC_ID)
) ;


CREATE TABLE R04_COL_ROL
(
  R04_COL_ID INTEGER UNSIGNED NOT NULL,
  R04_ROL_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_COL_ROL (R04_COL_ID, R04_ROL_ID),
  FOREIGN KEY FK_R04_COL (R04_COL_ID) REFERENCES COL_COLLABORATEUR (COL_ID),
  FOREIGN KEY FK_R04_ROL (R04_ROL_ID) REFERENCES ROL_ROLE (ROL_ID)
) ;


CREATE TABLE R05_COL_PRJ
(
  R05_COL_ID INTEGER UNSIGNED NOT NULL,
  R05_PRJ_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_R05_COL_PRJ (R05_COL_ID, R05_PRJ_ID),
  FOREIGN KEY FK_R05_COL (R05_COL_ID) REFERENCES COL_COLLABORATEUR (COL_ID),
  FOREIGN KEY FK_R05_PRJ (R05_PRJ_ID) REFERENCES PRJ_PROJET (PRJ_ID)
) ;



CREATE TABLE RIS_RISQUE
(
  RIS_ID              INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  RIS_NOM             VARCHAR(48)      NOT NULL,
  RIS_DESCRIPTION     TEXT             NULL,
  RIS_PRIORITE        INTEGER UNSIGNED NOT NULL,
  RIS_IMPACT          TEXT             NOT NULL,
  RIS_ETAT            TEXT             NOT NULL,
  RIS_PRJ_ID          INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_RIS_RISQUE (RIS_ID),
  FOREIGN KEY FK_RIS_PRJ (RIS_PRJ_ID) REFERENCES PRJ_PROJET (PRJ_ID)
) ;

CREATE TABLE MET_METRIQUE
(
  MET_ID          INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  MET_NOM         VARCHAR(48)      NOT NULL,
  MET_TYPE        INTEGER UNSIGNED NOT NULL,
  MET_VALEUR      INTEGER UNSIGNED NOT NULL,
  MET_DESCRIPTION TEXT             NULL,
  MET_PRJ_ID      INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_MET_METRIQUE (MET_ID),
  FOREIGN KEY FK_MET_PRJ (MET_PRJ_ID) REFERENCES PRJ_PROJET (PRJ_ID)
);

CREATE TABLE IMP_ACTIVITEIMP
(
  IMP_ID          INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  IMP_NOM         VARCHAR(48)      NOT NULL,
  IMP_DESCRIPTION TEXT             NOT NULL,
  PRIMARY KEY PK_IMP_ACTIVITEIMP (IMP_ID)
);

CREATE TABLE TCOL_TACHECOLLABORATIVE
(
  TCOL_ID              INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TCOL_NOM             VARCHAR(48)      NOT NULL,
  TCOL_DESCRIPTION     VARCHAR(48)      NULL,
  TCOL_CHARGEINITIALE  FLOAT            NOT NULL,
  TCOL_TEMPSPASSE      FLOAT            NOT NULL,
  TCOL_RESTEAPASSER    FLOAT            NOT NULL,
  TCOL_ETAT            INTEGER          NOT NULL,
  TCOL_DATEDEBUTPREVUE DATE             NOT NULL,
  TCOL_DATEFINPREVUE   DATE             NOT NULL,
  TCOL_DATEDEBUTREELLE DATE             NULL,
  TCOL_DATEFINREELLE   DATE             NULL,
  TCOL_ITE_ID          INTEGER UNSIGNED NOT NULL,
  TCOL_COL_ID          INTEGER UNSIGNED NOT NULL,
  TCOL_DATEDEBUTCHRONO DATE             NULL,
  PRIMARY KEY PK_TCOL_TACHE (TCOL_ID),
  FOREIGN KEY FK_TCOL_ITE (TCOL_ITE_ID) REFERENCES ITE_ITERATION (ITE_ID),
  FOREIGN KEY FK_TCOL_COL (TCOL_COL_ID) REFERENCES COL_COLLABORATEUR (COL_ID)
) ;

CREATE TABLE R06_COL_TCOL
(
  R06_COL_ID INTEGER UNSIGNED NOT NULL,
  R06_TCOL_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_R06_COL_TCOL(R06_COL_ID, R06_TCOL_ID),
  FOREIGN KEY FK_R06_COL (R06_COL_ID) REFERENCES COL_COLLABORATEUR (COL_ID),
  FOREIGN KEY FK_R06_TCOL (R06_TCOL_ID) REFERENCES TCOL_TACHECOLLABORATIVE (TCOL_ID)
) ;

CREATE TABLE PRB_PROBLEME
(
  PRB_ID                 INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PRB_DESCRIPTION        TEXT             NULL,
  PRB_ETAT               VARCHAR(48)      NULL,
  PRB_NOM                VARCHAR(48)      NOT NULL,
  PRB_DATEIDENTIFICATION DATE             NOT NULL,
  PRB_DATECLOTURE        DATE             NOT NULL,
  PRIMARY KEY PK_PRB_PROBLEME (PRB_ID)
);

CREATE TABLE R07_TAC_PRB_RESOUT
(
  R07_TAC_ID INTEGER UNSIGNED NOT NULL,
  R07_PRB_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_R07_TAC_PRB (R07_TAC_ID, R07_PRB_ID),
  FOREIGN KEY FK_R07_TAC (R07_TAC_ID) REFERENCES TAC_TACHE (TAC_ID),
  FOREIGN KEY FK_R07_PRB (R07_PRB_ID) REFERENCES PRB_PROBLEME (PRB_ID)
) ;

CREATE TABLE R08_TAC_PRB_PROVOQUE
(
  R08_TAC_ID INTEGER UNSIGNED NOT NULL,
  R08_PRB_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY PK_R08_TAC_PRB (R08_TAC_ID, R08_PRB_ID),
  FOREIGN KEY FK_R08_TAC (R08_TAC_ID) REFERENCES TAC_TACHE (TAC_ID),
  FOREIGN KEY FK_R08_PRB (R08_PRB_ID) REFERENCES PRB_PROBLEME (PRB_ID)
) ;


/******************************
 * Table de configuration. *
 ******************************/

 CREATE TABLE CON_CONFIGURATION
 (
   CON_ID              INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
   CON_LANGUE          VARCHAR(5) NOT NULL,
   CON_PAYS            VARCHAR(5) NOT NULL,
   CON_APPARENCE       VARCHAR(10) NOT NULL,
   CON_PATH_ARTEFACT   VARCHAR(48) NOT NULL,
   CON_PATH_SAUVEGARDE VARCHAR(48) NOT NULL,
   PRIMARY KEY PK_CON_CONFIGURTION(CON_ID) 
 ) ;
 